// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import java.io.Console;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class JA_Validate_Organization extends CustomJavaAction<java.lang.Boolean>
{
	/** @deprecated use Organization.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Organization;
	private final myfirstmodule.proxies.Oganization Organization;
	private final java.lang.Boolean IsValid;

	public JA_Validate_Organization(
		IContext context,
		IMendixObject _organization,
		java.lang.Boolean _isValid
	)
	{
		super(context);
		this.__Organization = _organization;
		this.Organization = _organization == null ? null : myfirstmodule.proxies.Oganization.initialize(getContext(), _organization);
		this.IsValid = _isValid;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
        String organizationName = this.Organization.getName();
        String location = this.Organization.getLocation();

        if (organizationName != null && !organizationName.isEmpty() && location != null && !location.isEmpty()) {
            return IsValid; 
        }else {
            return false;
        }
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_Validate_Organization";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
